// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
/*
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM8LqDzmqvg2lLghcBC1eWidEKercZHhE',
    appId: '1:555720783066:web:05e8b360b865d7d08921e3',
    messagingSenderId: '555720783066',
    projectId: 'jeff-talks',
    authDomain: 'jeff-talks.firebaseapp.com',
    storageBucket: 'jeff-talks.appspot.com',
    measurementId: 'G-Q15XHW074L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAMUEQK7oC9qPqzErBU4Bak0xoWyqMn0M',
    appId: '1:555720783066:android:7fda4106bc3de5b98921e3',
    messagingSenderId: '555720783066',
    projectId: 'jeff-talks',
    storageBucket: 'jeff-talks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbpshEBxGwBHHYXFBlU0hocSriHHrqvSo',
    appId: '1:555720783066:ios:1904d8047e07f6f78921e3',
    messagingSenderId: '555720783066',
    projectId: 'jeff-talks',
    storageBucket: 'jeff-talks.appspot.com',
    iosBundleId: 'com.example.jeffTalks',
  );
}
*/
